---
title: "Conferences and presentations"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Conferences and presentations}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r include=FALSE}
colorize <- function(x, color) {
  if (knitr::is_latex_output()) {
    sprintf("\\textcolor{%s}{%s}", color, x)
  } else if (knitr::is_html_output()) {
    sprintf("<span style='color: %s;'>%s</span>", color,
      x)
  } else x
}
```
```{r, include = FALSE}
knitr::opts_chunk$set(
  dev = "png",
  dpi = 150,
  fig.asp = 0.618,
  fig.width = 5,
  out.width = "60%",
  fig.align = "center",
  collapse = TRUE,
  comment = "#>"
)
```
```{r, include = FALSE}
install.packages("vembedr")
library(vembedr)
```

# `r colorize("Statistical quality control with QCR and ILS packages.","#1CA666")`

<br>

```{r warning=FALSE,echo=FALSE}
embed_youtube('mhUJh5Wz2X8', width=775, height=550)
```
<br>

# `r colorize("Salvador Naya Fernández | De Galicia a Ecuador. Ida e volta con R.","#1CA666")`

<br>

```{r warning=FALSE,echo=FALSE}
embed_youtube('-x7Kj6D141g', width=775, height=550)
```



